### ISSUE TITLE
Mixed content errors on HTTPS hosted GitHub Page

### ISSUE THREAD

**Issue by frewsxcv** [strava/iD#5]
https://strava.github.io/iD

e.g.:

> Mixed Content: The page at 'https://strava.github.io/iD/#background=Bing&map=16.31/-77.02304/38.90038' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://www.openstreetmap.org/api/0.6/map?bbox=-77.0361328125,38.89958342598271,-77.03063964843749,38.903858339667785'. This request has been blocked; the content must be served over HTTPS.

Could probably be fixed by utilizing protocol agnostic URLs (remove `http:` prefix)

(great talk at SOTMUS 2015 @paulmach !)

**Comment by paulmach** [comment]
I think that's an issue with iD in general. Looks to be hard coded https://github.com/openstreetmap/iD/blob/76089be464d14527802bb45301aa42e9a75719b2/js/id/core/connection.js#L3

FYI @bhousel

**Comment by frewsxcv** [comment]
FWIW, https://github.com/openstreetmap/iD/issues/2681 has merged

**Comment by paulmach** [comment]
Sweet thanks. All :green_heart: now. https://strava.github.io/iD/

**Comment by paulmach** [comment]
Updated the "slide" server to use HTTPS.  That's the only think I know of that was http.  Let me know if you find anything else.
