### ISSUE TITLE
Can't authenticate

### ISSUE THREAD

**Issue by sabas** [strava/iD#6]
When I open iD, it doesn't ask me to login, and when I try to save I get an error 401 (unauthorized)

![image](https://cloud.githubusercontent.com/assets/1304918/11815809/ca29f994-a34d-11e5-8f51-9bb0a88f965e.png)

**Comment by paulmach** [comment]
hum. I just tested it and was able to login and save. Maybe clear the local storage for strava.github.io to reset stuff. Maybe something changed between version updates that's causing issues. 

I upgraded iD from 1.8.0 -> 1.8.3 last sunday.

**Comment by sabas** [comment]
Deleted cookies + local storage from strava.github.io and it works now, thanks!
